# The following is automatically generated by code_factory.py

from numba import njit


@njit
def flat_data(index, photon_material, data):
    offset = photon_material["flat_data_offset"]
    return data[offset + index]


@njit
def flat_data_all(photon_material, data):
    start = photon_material["flat_data_offset"]
    size = photon_material["flat_data_length"]
    end = start + size
    return data[start:end]


@njit
def flat_data_last(photon_material, data):
    start = photon_material["flat_data_offset"]
    size = photon_material["flat_data_length"]
    end = start + size
    return data[end - 1]


@njit
def flat_data_chunk(start, length, photon_material, data):
    start += photon_material["flat_data_offset"]
    end = start + length
    return data[start:end]
