# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, photon_reaction, data):
    offset = photon_reaction["xs_offset"]
    return data[offset + index]


@njit
def xs_all(photon_reaction, data):
    start = photon_reaction["xs_offset"]
    size = photon_reaction["xs_length"]
    end = start + size
    return data[start:end]


@njit
def xs_last(photon_reaction, data):
    start = photon_reaction["xs_offset"]
    size = photon_reaction["xs_length"]
    end = start + size
    return data[end - 1]


@njit
def xs_chunk(start, length, photon_reaction, data):
    start += photon_reaction["xs_offset"]
    end = start + length
    return data[start:end]
