# The following is automatically generated by code_factory.py

from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def xs(index, proton_reaction, data):
    offset = proton_reaction["xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def xs_all(proton_reaction, data):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def xs_last(proton_reaction, data):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def xs_chunk(start, length, proton_reaction, data):
    start += proton_reaction["xs_offset"]
    end = start + length
    return array_result(data[start:end])
