# The following is automatically generated by code_factory.py

from numba import njit


@njit
def flat_data(index, photon_material, data, value):
    offset = photon_material["flat_data_offset"]
    data[offset + index] = value


@njit
def flat_data_all(photon_material, data, value):
    start = photon_material["flat_data_offset"]
    size = photon_material["flat_data_length"]
    end = start + size
    data[start:end] = value


@njit
def flat_data_last(photon_material, data, value):
    start = photon_material["flat_data_offset"]
    size = photon_material["flat_data_length"]
    end = start + size
    data[end - 1] = value


@njit
def flat_data_chunk(start, length, photon_material, data, value):
    start += photon_material["flat_data_offset"]
    end = start + length
    data[start:end] = value
